
# latin color word list from: http://www.coolschool.k12.or.us/courses/121510/lessons/assignments/13/13-4.latincolor.html
COLORS = set(['aeruginosus','albus','albidus','albicans','amethystinus','argenteus','argyraeus','atamasco','ater','atomarius','atratus','atropureus','atrosanguineus','atroviolacens','atrovirens','aurantiacus','aureolus','aureus','auricomus','azureus','bruneus','caeruleus','caesius','canarius','candidus','canus','cardinalis','carminatus','carneus','castaneus','cerasinus','cerinus','cervinus','cheiri','chloranthus','chryseus','chrysoleucus','chrystostomus','cineraceus','cinereus','cinnabarinus','cinnamomeus','citrinus','coelestinus','coloratus','concolor','coracinus','corallinus','crocatus','croceus','cruentus','cupreatus','cyaneus','cypreus','decolorans','dichrous','dilutus','discolor','diversicolor','ebenus','eburneus','erubescens','erythraeus','erythrocephalus','estriatus','euchlorus','euchromus','ferrugineus','festivus','flammeus','flavescens','flavidus','flavovirens','flavus','florealbo','fucatus','fulgens','fulgidus','fulvidus','fulvus','fumidus','fuscus','galanthus','galbinus','griseus','guttatus','haemanthus','hibernus','holochrysus','hyacinthinus','hyalinus','ictericus','ignescens','immaculatus','incanus','incarnatus','isabellinus','inquinans','laetesvirens','laetus','lateritus','leopardinus','leprosus','leucanthus','leucophaeus','leucoxylon','lilacinus','limpidus','lividus','lucidus','maculatus','malvinus','margaritaceus','melanocentris','mesoleucus','micans','miniatus','niger','nitens','nivalis','ochraceus','ochroleucus','opacus','palleus','palliflaveus','pavoninus','phaeus','phoenicus','piceus','plumbeus','porphyreus','prasinus','pullus','puniceus','quadricolor','ravus','refulgens','rubens','rubicundus','rufescens','rufus','russatus','rutilans','sanguineus','scariosus','sempervirens','senilis','smaragdinus','stramineus','subcaerulus','sulphureus','testaceus','tinctus','tricolor','unicolor','versicolor','vernus','violaceus','violacens','virens','virescens','viridescens','viridifuscus','viridis','viridulus','vittigera','xanthinus','zebrinus'])
COLOR_STEMS = set(['rube', 'blav', 'aeruginos','alb','albid','albicant','amethystin','argente','argyrae','atamasco','ater','atomari','atrat','atropure','atrosanguine','atroviolacent','atrovirent','aurantiac','aureol','aure','auricom','azure','brune','caerule','caesi','canari','candid','can','cardinalis','carminat','carne','castane','cerasin','cerin','cervin','cheiri','chloranth','chryse','chrysoleuc','chrystostom','cinerace','cinere','cinnabarin','cinnamome','citrin','coelestin','colorat','concolor','coracin','corallin','crocat','croce','cruent','cupreat','cyane','cypre','decolorant','dichro','dilut','discolor','diversicolor','eben','eburne','erubescent','erythrae','erythrocephal','estriat','euchlor','euchrom','ferrugine','festiv','flamme','flavescent','flavid','flavovirent','flav','florealbo','fucat','fulgent','fulgid','fulvid','fulv','fumid','fusc','galanth','galbin','grise','guttat','haemanth','hibern','holochrys','hyacinthin','hyalin','icteric','ignescent','immaculat','incan','incarnat','isabellin','inquinant','laetesvirent','laet','laterit','leopardin','lepros','leucanth','leucophae','leucoxylon','lilacin','limpid','livid','lucid','maculat','malvin','margaritace','melanocentris','mesoleuc','micant','miniat','niger','nitent','nivalis','ochrace','ochroleuc','opac','palle','palliflave','pavonin','phae','phoenic','pice','plumbe','porphyre','prasin','pull','punice','quadricolor','rav','refulgent','rubent','rubicund','rufescent','ruf','russat','rutilant','sanguine','scarios','sempervirent','senilis','smaragdin','stramine','subcaerul','sulphure','testace','tinct','tricolor','unicolor','versicolor','vern','violace','violacent','virent','virescent','viridescent','viridifusc','viridis','viridul','vittigera','xanthin','zebrin']) 
#SUBSTRATES = set(['ferri', 'cupri', 'pumbli', 'panni', 'vitri', 'auri', 'argenti', 'lictoni', 'letonis', 'lotoni', 'stagni', 'cirici', 'sirici', 'burelli'])
SUBSTRATE_STEMS = set(['plumb', 'vitre', 'aure', 'ciric', 'fust', 'ferri', 'cupr', 'feurr','ferr', 'pann', 'vitr', 'aur', 'argenti', 'licton', 'leton', 'loton', 'stagn', 'ciric', 'siric', 'burell', 'eram', 'core', 'cere', 'nunce', 'sapp', 'pin', 'lin', 'lan', 'ebor', 'canap', 'scurol', 'squirrol'])
ACCESSORY_STEMS =  set(['folrat', 'foderat', 'complet', 'armigerat'])

CONTENTS = set(['vini', 'melli', 'aceti', 'fabarum', 'cinere', 'sinere'])
CONTENTS_STEMS = set(['vacu', 'tonin'])

NUMBER_STEMS = set([])

STYLES = set(['damascino'])
STYLE_STEMS = set(['superdeaurat', 'listat', 'clavat', 'perforat', 'daurat'])

# the quidam is not comprehensive
NUMBER_STEMS = set(['un', 'du', 'tr', 'quattuor', 'quinque', 'sex', 'septem', 'octo', 'novem', 'decem', 'ali', 'quidam', 'quadam', 'quodam'])


FUNCTION_STEMS = set(['navigand', 'ponend', 'fariner', 'circuland', 'selcland', 'appotopand', 'ronhand', 'bugader', 'portand', 'faciend', 'planand', 'tenend', 'aygader', 'salandaum', 'meler', 'piscibus', 'pissibus', 'lavand', 'ponderand', 'trahend', 'saumat', 'perand', 'venand', 'moland', 'amoland', 'comedend'])